Repository hiker-s/hikers-FE, pull requests merged in 2025-05, with the labels that each got.

#57 56 feat rank 페이지 api 연동
  src/apis/rank/RankApi.tsx
  src/components/common/modal/ShareModal.styled.ts
  src/components/common/modal/ShareModal.tsx
  src/components/course/courseInfo/CourseData.tsx
  src/components/rank/RankList.tsx
  src/components/rank/Ranker.tsx
  src/components/rank/Top3.tsx
Labels: 📬 API, ⛰️ 동은

#58 Fix: dataModule import 3-2-1) 방식 주석처리 (경고 해결)
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/SketchMap.tsx
Labels: 🐞 Fix

#61 feat: loading 및 not found 페이지 UI 구현
  package-lock.json
  package.json
  src/assets/images/LoadingBg.svg
  src/pages/error/NotFound.tsx
  src/pages/loading/Loading.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#63 fix: 산 배너 스타일 오류 해결
  src/components/course/courseList/MountainBanner.styled.ts
  src/components/course/courseList/MountainBanner.tsx
Labels: 🎨 Design, 🐞 Fix, ⛰️ 윤정

#64 리뷰 작성 / 수정 UI 구현 및 연동
  package-lock.json
  src/apis/community/ReviewApi.tsx
  src/apis/community/ReviewSearchApi.tsx
  src/assets/icons/mountainMove.svg
  src/components/common/card/CardList.tsx
  src/components/common/card/styled.ts
  src/components/common/filter/Filter.styled.ts
  src/components/common/filter/Filter.tsx
  src/components/common/filter/review/CourseFilter.tsx
  src/components/common/filter/review/MountainFilter.tsx
  src/components/common/filter/review/ReviewFilter.styled.ts
  src/components/common/footer/styled.ts
  src/components/community/CommunityReview.tsx
  src/components/community/review/ReviewEditForm.tsx
  src/components/community/review/ReviewForm.tsx
  src/components/community/review/styled.ts
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/CourseReview.tsx
  src/components/course/courseInfo/SketchMap.tsx
  src/components/course/courseList/MountainReview.tsx
  src/components/home/FamousMountain.tsx
  src/hooks/useNaverMap.ts
  src/pages/community/review/ReviewEdit.tsx
  src/pages/community/review/ReviewWrite.tsx
  src/router.tsx
Labels: 🎨 Design, 🐞 Fix, 📬 API, ⛰️ 동은

#66 fix: 리뷰 삭제 시 경로 이동 오류 해결
  src/apis/community/CrewApi.tsx
  src/apis/rank/RankApi.tsx
  src/components/common/list/CourseList.tsx
  src/components/community/review/ReviewEditForm.tsx
  src/components/rank/RankList.tsx
  src/components/rank/Top3.tsx
  src/hooks/useNaverMap.ts
  src/pages/community/review/ReviewEdit.tsx
Labels: 🐞 Fix, ⛰️ 윤정

#69 Fix: search.tsx 컴포넌트 배포 중 오류 해결
  src/components/home/Search.tsx
Labels: 🌏 Deploy, 🐞 Fix, ⛰️ 윤정

#72 Dev: 프로그램 데이터 추가
  public/assets/program/poster/poster01.svg
  public/assets/program/poster/poster02.svg
  public/assets/program/poster/poster03.svg
  public/assets/program/poster/poster04.svg
  public/assets/program/poster/poster05.svg
  public/assets/program/poster/poster06.svg
  public/assets/program/poster01.svg
  public/assets/program/programPoster.svg
  public/assets/program/thumbnail/thumbnail01.svg
  public/assets/program/thumbnail/thumbnail02.svg
  public/assets/program/thumbnail/thumbnail03.svg
  public/assets/program/thumbnail/thumbnail04.svg
  public/assets/program/thumbnail/thumbnail05.svg
  public/assets/program/thumbnail/thumbnail06.svg
  public/assets/program/thumbnailPoster.svg
  src/data/program-dummy.json
Labels: ✨ Feature, 🌏 Deploy, ⛰️ 윤정

#75 Fix: 실시간 도시데이터 Mixed content 에러 해결
  index.html
Labels: 🐞 Fix, ⛰️ 동은

#78 Comment: json 파일 불러오는 다양한 방법 주석으로 추가
  src/components/course/courseInfo/CourseData.tsx
Labels: 🐞 Fix, ⛰️ 동은

#79 Fix: 동적 import 방식 수정 (Vite의 import.meta.glob 활용)
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/DetailCourseList.tsx
  src/components/course/courseInfo/SketchMap.tsx
Labels: 🐞 Fix, ⛰️ 동은

#80 Design: CardListBottomWrapper에 padding 추가
  src/components/course/courseList/MountainReview.tsx
Labels: 🐞 Fix, ⛰️ 동은

#81 Fix: 실시간 도시데이터 (날씨) 백엔드 api 연동으로 변경 구현
  src/apis/home/WeatherApi.tsx
  src/components/home/Weather.tsx
Labels: 🐞 Fix, 📬 API, ⛰️ 동은

#82 Fix: 커뮤니티 - 크루 글 리스트 최신순으로 보이게 설정
  src/apis/community/CrewApi.tsx
Labels: 🐞 Fix, ⛰️ 윤정

#83 Fix: 리뷰 좋아요 클릭 연동
  src/components/common/card/CardList.tsx
Labels: 📬 API, ⛰️ 동은

#84 Fix: 리뷰 카드 자세히보기 navigate 함수 추가
  src/components/common/card/CardList.tsx
Labels: 🐞 Fix

#90 Fix: 스탬프 svg 이미지 깨짐 오류 해결 1차 시도
  src/components/mypage/Stamp.styled.ts
Labels: 🎨 Design, 🐞 Fix, ⛰️ 윤정

#94 UX: 사파리 font 깨짐 해결 (가중치 범위 조정, 폰트 합성 비활성화)
  src/style/global.ts
Labels: 🐞 Fix, ⛰️ 동은

#95 89 fix safari 브라우저에서 이미지 오류 해결
  src/components/mypage/Stamp.styled.ts
Labels: 🎨 Design, 🐞 Fix, ⛰️ 윤정

#96 fix: safari 브라우저에서 이미지 오류 해결
  src/components/mypage/Stamp.styled.ts
Labels: 🌏 Deploy, 🎨 Design, 🐞 Fix, ⛰️ 윤정

#97 fix: safari 브라우저에서 이미지 오류 해결
  public/assets/stamp/bookhansan.png
  public/assets/stamp/eungbongsan.png
  public/assets/stamp/gwanaksan.png
  public/assets/stamp/hallasan.png
  public/assets/stamp/jooheulsan.png
  public/assets/stamp/joowangsan.png
  public/assets/stamp/manisan.png
  public/assets/stamp/naejangsan.png
  public/assets/stamp/naeyeonsan.png
  public/assets/stamp/palgongsan.png
  public/assets/stamp/seolaksan.png
  src/components/mypage/Stamp.styled.ts
  src/components/mypage/Stamp.tsx
Labels: 🎨 Design, 🐞 Fix, ⛰️ 윤정

#98 fix: safari 브라우저에서 이미지 오류 해결 시도
  public/assets/stamp/bookhansan.png
  public/assets/stamp/eungbongsan.png
  public/assets/stamp/gwanaksan.png
  public/assets/stamp/hallasan.png
  public/assets/stamp/jooheulsan.png
  public/assets/stamp/joowangsan.png
  public/assets/stamp/manisan.png
  public/assets/stamp/naejangsan.png
  public/assets/stamp/naeyeonsan.png
  public/assets/stamp/palgongsan.png
  public/assets/stamp/seolaksan.png
  src/components/mypage/Stamp.styled.ts
  src/components/mypage/Stamp.tsx
Labels: 🌏 Deploy, 🐞 Fix, ⛰️ 윤정

#99 Chore: 스탬프 이미지 png 파일 수정
  public/assets/stamp/bookhansan.png
  public/assets/stamp/eungbongsan.png
  public/assets/stamp/gwanaksan.png
  public/assets/stamp/hallasan.png
  public/assets/stamp/jooheulsan.png
  public/assets/stamp/joowangsan.png
  public/assets/stamp/manisan.png
  public/assets/stamp/naejangsan.png
  public/assets/stamp/naeyeonsan.png
  public/assets/stamp/palgongsan.png
  public/assets/stamp/seolaksan.png
  src/components/mypage/Stamp.styled.ts
Labels: 🎨 Design, ⛰️ 윤정

#100 Chore: 스탬프 이미지 png 파일 수정
  public/assets/stamp/bookhansan.png
  public/assets/stamp/eungbongsan.png
  public/assets/stamp/gwanaksan.png
  public/assets/stamp/hallasan.png
  public/assets/stamp/jooheulsan.png
  public/assets/stamp/joowangsan.png
  public/assets/stamp/manisan.png
  public/assets/stamp/naejangsan.png
  public/assets/stamp/naeyeonsan.png
  public/assets/stamp/palgongsan.png
  public/assets/stamp/seolaksan.png
  src/components/mypage/Stamp.styled.ts
Labels: 🌏 Deploy, 🎨 Design, ⛰️ 윤정

#101 Chore: 스탬프 이미지 png 파일 수정
  public/assets/stamp/bookhansan.png
  public/assets/stamp/eungbongsan.png
  public/assets/stamp/gwanaksan.png
  public/assets/stamp/hallasan.png
  public/assets/stamp/jooheulsan.png
  public/assets/stamp/joowangsan.png
  public/assets/stamp/manisan.png
  public/assets/stamp/naejangsan.png
  public/assets/stamp/naeyeonsan.png
  public/assets/stamp/palgongsan.png
  public/assets/stamp/seolaksan.png
  src/components/mypage/Stamp.styled.ts
Labels: 🌏 Deploy, 🎨 Design, ⛰️ 윤정

#102 Fix: 자세히보기 버튼 navigate 수정
  src/components/common/card/CardList.tsx
Labels: 🐞 Fix

#104 feat: 웹 메타 정보 설정
  index.html
  public/hikers.png
  src/components/mypage/Stamp.styled.ts
Labels: ✨ Feature, 📃 Docs, ⛰️ 윤정

#105 feat: 웹 메타 정보 설정
  index.html
  public/hikers.png
  src/components/mypage/Stamp.styled.ts
Labels: 🌏 Deploy, 📃 Docs, ⛰️ 윤정

#107 Fix: seo 이미지 안뜨는 오류 수정
  index.html
Labels: 🐞 Fix, ⛰️ 윤정

#109 fix: 카카오톡 공유하기 모달 스타일 오류 수정
  src/components/common/modal/ShareModal.styled.ts
  src/components/common/modal/ShareModal.tsx
Labels: 🎨 Design, 🐞 Fix, ⛰️ 윤정

#110 Fix: 공유하기 모달 컨텐츠 왼쪽 쏠림 현상 해결
  src/components/common/modal/ShareModal.styled.ts
  src/components/common/modal/ShareModal.tsx
Labels: 🌏 Deploy, 🎨 Design, 🐞 Fix, ⛰️ 윤정

#112 fix: 코스인포 페이지 오류 해결
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/DetailCourseList.tsx
Labels: 🐞 Fix, 🔨 Refactor, ⛰️ 윤정

#113 fix: 코스인포 페이지 오류 해결
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/DetailCourseList.tsx
Labels: 🌏 Deploy, 🐞 Fix, 🔨 Refactor, ⛰️ 윤정

#115 fix 코스인포 페이지 오류 해결
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/DetailCourseList.tsx
Labels: 🌏 Deploy, 🐞 Fix, ⛰️ 윤정

#117 Chore: 코스 인포 페이지 카테고리 스크롤 수정
  src/components/common/header/Header.tsx
  src/pages/course/CourseInfo.tsx
Labels: 🌏 Deploy, 🐞 Fix, 🔨 Refactor, ⛰️ 윤정

#118 Test: 코스 인포 페이지 디버깅을 위한 상세코스 코드 주석처리
  src/pages/course/CourseInfo.tsx
Labels: 🐞 Fix, ⛰️ 윤정

#119 Test: 코스 인포 페이지 디버깅을 위한 상세코스 코드 주석처리
  src/pages/course/CourseInfo.tsx
Labels: 🐞 Fix, ⛰️ 윤정

#120 fix: 코스인포 페이지 오류 해결 시도중
  src/components/course/courseInfo/DetailCourseList.tsx
  src/components/course/courseInfo/RoadView.tsx
  src/pages/course/CourseInfo.tsx
Labels: 🐞 Fix, ⛰️ 윤정

#121 fix: 코스인포 페이지 오류 해결 시도중
  src/components/course/courseInfo/DetailCourseList.tsx
  src/components/course/courseInfo/RoadView.tsx
  src/pages/course/CourseInfo.tsx
Labels: 🐞 Fix, ⛰️ 윤정

#122 Design: courseInfo 페이지 스타일 재설정
  src/components/common/card/styled.ts
  src/components/course/courseInfo/CourseReview.tsx
  src/components/course/courseList/MountainReview.tsx
Labels: 🌏 Deploy, 🎨 Design, ⛰️ 윤정

#123 Fix: 코스 리뷰 컴포넌트 스타일 오류 수정
  src/components/common/card/styled.ts
  src/components/course/courseList/CourseListComp.styled.ts
  src/components/course/courseList/MountainReview.tsx
  src/pages/course/CourseList.tsx
Labels: 🌏 Deploy, 🎨 Design, 🐞 Fix, ⛰️ 윤정

#124 Design: 산 리뷰 데이터 없는 경우 width 스타일 제거
  src/components/course/courseList/MountainReview.tsx
  src/pages/course/CourseList.tsx
Labels: 🌏 Deploy, 🎨 Design, 🐞 Fix, ⛰️ 윤정

#125 Design: 리뷰 작성 input창 크기 확대
  src/components/community/review/styled.ts
Labels: 🎨 Design, ⛰️ 동은

#126 Fix: back 버튼 navigate(-1)로 수정
  src/pages/community/crew/CrewRead.tsx
  src/pages/community/crew/CrewWrite.tsx
  src/pages/community/review/ReviewRead.tsx
  src/pages/community/review/ReviewWrite.tsx
Labels: 🐞 Fix, ⛰️ 동은

#128 Fix: 413 Request Entity Too Large 에러처리
  src/pages/community/crew/CrewEdit.tsx
  src/pages/community/crew/CrewWrite.tsx
  src/pages/community/review/ReviewEdit.tsx
  src/pages/community/review/ReviewWrite.tsx
Labels: 🐞 Fix, ⛰️ 동은

#129 fix 커뮤니티 스타일 오류 수정
  src/components/community/read/styled.ts
  src/pages/community/crew/CrewRead.tsx
  src/pages/community/review/ReviewRead.tsx
Labels: 🎨 Design, 🐞 Fix, ⛰️ 윤정

#130 Fix: 커뮤니티 스타일 오류 수정
  src/components/community/read/styled.ts
  src/pages/community/crew/CrewRead.tsx
  src/pages/community/review/ReviewRead.tsx
Labels: 🌏 Deploy, 🎨 Design, 🐞 Fix, ⛰️ 윤정
