Repository hiker-s/hikers-FE, pull requests merged in 2025-04, with the labels that each got.

#3 Feat: BottomBtn, Input, Header 공통컴포넌트 구현 및 로그인,온보딩 페이지 UI 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/App.tsx
  src/assets/Onboarding.svg
  src/assets/backBtn.svg
  src/assets/logo.svg
  src/assets/mountainLogo.svg
  src/components/common/button/BottomBtn.tsx
  src/components/common/button/styled.ts
  src/components/common/header/Header.tsx
  src/components/common/header/styled.ts
  src/components/common/input/Input.tsx
  src/components/common/input/styled.ts
  src/components/common/logo/Logo.tsx
  src/components/common/logo/MountainLogo.tsx
  src/components/common/logo/styled.ts
  src/components/onboarding/NotMemberYet.tsx
  src/components/onboarding/styled.ts
  src/index.css
  src/main.tsx
  src/pages/login/Login.tsx
  src/pages/login/styled.ts
  src/pages/onboarding/Onboarding.tsx
  src/pages/onboarding/styled.ts
  src/router.tsx
  src/style/global.ts
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#7 Feat: 회원가입 페이지 UI 구현 및 로드뷰 컴포넌트 구현
  .gitignore
  public/fonts/PretendardVariable.woff2
  src/assets/Onboarding.svg
  src/assets/greyBackground.svg
  src/components/course/courseInfo/RoadView.tsx
  src/components/course/courseInfo/styled.ts
  src/pages/login/Login.tsx
  src/pages/signup/SignUp.tsx
  src/pages/signup/Success.tsx
  src/pages/signup/styled.ts
  src/router.tsx
  src/style/global.ts
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#15 코스 페이지(CourseList, CourseInfo) UI 구현 완료
  .gitignore
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/GreenHeart.svg
  src/assets/WhiteHeart.svg
  src/assets/filter.svg
  src/components/common/button/GreenBtn.tsx
  src/components/common/button/styled.ts
  src/components/common/card/Card.tsx
  src/components/common/card/CardList.tsx
  src/components/common/card/styled.ts
  src/components/common/filter/Filter.tsx
  src/components/common/filter/styled.ts
  src/components/common/header/styled.ts
  src/components/common/item/Level.tsx
  src/components/common/item/styled.ts
  src/components/common/layout/styled.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/styled.ts
  src/components/course/courseInfo/CourseData.styled.ts
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/CourseReview.tsx
  src/components/course/courseInfo/SketchMap.styled.ts
  src/components/course/courseInfo/SketchMap.tsx
  src/components/course/courseList/CourseList.styled.ts
  src/components/course/courseList/CourseList.tsx
  src/components/course/courseList/CourseReview.tsx
  src/components/course/courseList/MountainBanner.styled.ts
  src/components/course/courseList/MountainBanner.tsx
  src/main.tsx
  src/pages/course/CourseInfo.styled.ts
  src/pages/course/CourseInfo.tsx
  src/pages/course/CourseList.styled.ts
  src/pages/course/CourseList.tsx
  src/pages/onboarding/styled.ts
  src/router.tsx
  vite-env.d.ts
Labels: ✨ Feature, 🎨 Design, ⛰️ 동은

#16 Feat: Footer 컴포넌트 구현
  src/assets/icons/Community.svg
  src/assets/icons/GreenHeart.svg
  src/assets/icons/Home.svg
  src/assets/icons/My.svg
  src/assets/icons/Rank.svg
  src/assets/icons/WhiteHeart.svg
  src/assets/icons/backBtn.svg
  src/assets/icons/filter.svg
  src/assets/images/greyBackground.svg
  src/assets/images/logo.svg
  src/assets/images/mountainLogo.svg
  src/assets/images/squareBaseImg.svg
  src/components/common/card/Card.tsx
  src/components/common/card/styled.ts
  src/components/common/filter/Filter.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/footer/styled.ts
  src/components/common/header/Header.tsx
  src/components/common/item/CourseItem.tsx
  src/components/common/item/CrewItem.tsx
  src/components/common/item/ReviewItem.tsx
  src/components/common/layout/Layout.tsx
  src/components/common/layout/styled.ts
  src/components/common/logo/Logo.tsx
  src/components/common/logo/MountainLogo.tsx
  src/pages/community/Community.tsx
  src/pages/course/CourseInfo.tsx
  src/pages/course/CourseList.tsx
  src/pages/login/Login.tsx
  src/pages/signup/Success.styled.ts
Labels: ✨ Feature, 🎨 Design, ⛰️ 동은

#18 Feat: 커뮤니티 페이지 UI 구현 및 캐러셀, 카테고리바 컴포넌트 구현
  package-lock.json
  package.json
  public/assets/program/thumbnailPoster.svg
  src/assets/images/squareBaseImg.svg
  src/components/common/header/Header.tsx
  src/components/common/header/styled.ts
  src/components/common/item/CourseItem.tsx
  src/components/common/item/ReviewItem.tsx
  src/components/common/item/styled.ts
  src/components/course/courseList/CourseList.tsx
  src/components/crew/CrewList.tsx
  src/components/program/Carousel.styled.ts
  src/components/program/Carousel.tsx
  src/components/review/ReviewList.tsx
  src/dummy/carousel.json
  src/pages/community/Community.styled.ts
  src/pages/community/Community.tsx
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#19 Feat: 커뮤니티 페이지 스크롤 위치에 따른 카테고리바 활성화 기능 설정
  src/components/common/header/Header.tsx
  src/pages/community/Community.tsx
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#21 Design: 커뮤니티 페이지 padding 조정
  src/pages/community/Community.tsx
Labels: 🎨 Design

#22 Feat: course info 페이지 UI 구현 마무리 및 상세코스 컴포넌트 구현
  src/components/common/header/Header.tsx
  src/components/course/courseInfo/DetailCourseList.styled.ts
  src/components/course/courseInfo/DetailCourseList.tsx
  src/components/course/courseInfo/RoadView.styled.ts
  src/components/course/courseInfo/RoadView.tsx
  src/pages/course/CourseInfo.styled.ts
  src/pages/course/CourseInfo.tsx
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#25 Feat: 프로그램 페이지 UI 구현
  public/assets/program/programPoster.svg
  src/components/program/Carousel.tsx
  src/dummy/carousel.json
  src/pages/program/Program.tsx
  src/pages/program/styled.ts
  src/router.tsx
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#29 Refactor: 리스트 컴포넌트 리팩토링
  src/components/common/footer/Footer.tsx
  src/components/common/list/CourseList.styled.ts
  src/components/common/list/CourseList.tsx
  src/components/common/list/CrewList.styled.ts
  src/components/common/list/CrewList.tsx
  src/components/common/list/ReviewList.styled.ts
  src/components/common/list/ReviewList.tsx
  src/components/community/CommunityCrew.tsx
  src/components/community/CommunityReview.tsx
  src/components/course/courseList/CourseListComp.styled.ts
  src/components/course/courseList/CourseListComp.tsx
  src/components/mypage/UserInfo.styled.ts
  src/components/mypage/UserInfo.tsx
  src/pages/course/CourseList.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/styled.ts
  src/router.tsx
Labels: 🔨 Refactor, ⛰️ 윤정

#32 Feat: 크루 글 조회 작성 페이지 UI 구현
  src/components/common/list/CrewList.tsx
  src/components/common/list/ReviewList.tsx
  src/components/community/CommunityCrew.tsx
  src/components/community/CommunityReview.tsx
  src/components/community/crew/CrewForm.styled.ts
  src/components/community/crew/CrewForm.tsx
  src/components/community/read/ButtonGroup.tsx
  src/components/community/read/PostContent.tsx
  src/components/community/read/PostCreateInfo.tsx
  src/components/community/read/PostReviewInfo.tsx
  src/components/community/read/PostTitle.tsx
  src/components/community/read/styled.ts
  src/constants/communityPlaceholder.ts
  src/pages/community/crew/CrewRead.styled.ts
  src/pages/community/crew/CrewRead.tsx
  src/pages/community/crew/CrewWrite.styled.ts
  src/pages/community/crew/CrewWrite.tsx
  src/pages/community/review/ReviewRead.styled.ts
  src/pages/community/review/ReviewRead.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Design, ⛰️ 윤정

#33 홈 페이지 UI 구현
  src/assets/icons/mountainRankDown.svg
  src/assets/icons/mountainRankFilter.svg
  src/assets/icons/mountainRankFilterClose.svg
  src/assets/icons/mountainRankSame.svg
  src/assets/icons/mountainRankUp.svg
  src/assets/icons/search.svg
  src/components/common/layout/Layout.tsx
  src/components/common/layout/styled.ts
  src/components/common/modal/SearchErrorModal.styled.ts
  src/components/common/modal/SearchErrorModal.tsx
  src/components/home/FamousMountain.tsx
  src/components/home/Search.styled.ts
  src/components/home/Search.tsx
  src/components/home/Weather.tsx
  src/pages/community/Community.tsx
  src/pages/community/crew/CrewRead.tsx
  src/pages/community/crew/CrewWrite.tsx
  src/pages/community/program/Program.tsx
  src/pages/community/review/ReviewRead.tsx
  src/pages/course/CourseInfo.tsx
  src/pages/course/CourseList.tsx
  src/pages/home/Home.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/rank/Rank.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Design, 📬 API, ⛰️ 동은

#37 Feat: 크루&리뷰 글 조회(이미지), 크루 수정 페이지 구현 및 변동사항 반영
  public/assets/program/poster01.svg
  public/assets/stamp/stampImage.svg
  src/components/common/item/CourseItem.tsx
  src/components/common/item/CrewItem.tsx
  src/components/common/item/ReviewItem.tsx
  src/components/common/item/styled.ts
  src/components/common/list/CourseList.tsx
  src/components/common/list/ReviewList.tsx
  src/components/community/CommunityReview.tsx
  src/components/community/crew/CrewForm.tsx
  src/components/community/read/ButtonGroup.tsx
  src/components/community/read/PostCreateInfo.tsx
  src/components/community/read/PostReviewInfo.tsx
  src/components/course/courseInfo/DetailCourseList.styled.ts
  src/components/course/courseInfo/DetailCourseList.tsx
  src/components/mypage/ButtonGroup.tsx
  src/components/mypage/DeleteAccountModal.styled.ts
  src/components/mypage/DeleteAccountModal.tsx
  src/components/mypage/LikedList.styled.ts
  src/components/mypage/LikedList.tsx
  src/components/mypage/MyReviewList.styled.ts
  src/components/mypage/MyReviewList.tsx
  src/components/mypage/ScrapedList.styled.ts
  src/components/mypage/ScrapedList.tsx
  src/components/mypage/Stamp.styled.ts
  src/components/mypage/Stamp.tsx
  src/components/mypage/UserInfo.styled.ts
  src/components/mypage/UserInfo.tsx
  src/data/program-dummy.json
  src/hooks/useImageUpload.ts
  src/pages/community/crew/CrewEdit.tsx
  src/pages/community/crew/CrewRead.styled.ts
  src/pages/community/crew/CrewRead.tsx
  src/pages/community/crew/CrewWrite.styled.ts
  src/pages/community/crew/CrewWrite.tsx
  src/pages/community/review/ReviewRead.styled.ts
  src/pages/community/review/ReviewRead.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/styled.ts
  src/router.tsx
Labels: ✨ Feature, 🎨 Design, 🔨 Refactor, ⛰️ 윤정

#38 [Refactor] courseInfo, courseList 리팩토링 및 static으로
  .gitignore
  src/components/common/modal/SearchErrorModal.tsx
  src/components/course/courseInfo/CourseData.styled.ts
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/SketchMap.tsx
  src/components/course/courseList/MountainBanner.tsx
  src/components/rank/RankList.tsx
  src/components/rank/Ranker.tsx
  src/components/rank/Top3.tsx
  src/hooks/useKakaoShare.ts
  src/hooks/useNaverMap.ts
  src/pages/course/CourseInfo.styled.ts
  src/pages/course/CourseInfo.tsx
  src/pages/course/CourseList.styled.ts
  src/pages/course/CourseList.tsx
  src/types/kakaoShare.d.ts
  src/types/mountainData.d.ts
  src/types/naverMap.d.ts
Labels: 🔨 Refactor, ⛰️ 동은

#41 feat: 회원가입 로그인 api 연동
  package-lock.json
  package.json
  src/apis/.gitkeep
  src/apis/account/AccountApi.tsx
  src/pages/login/Login.tsx
  src/pages/signup/SignUp.tsx
Labels: 📬 API, ⛰️ 윤정

#44 feat: 회원탈퇴, 로그아웃, 유저정보 api 연동
  src/apis/account/AccountApi.tsx
  src/apis/mypage/MypageApi.tsx
  src/components/common/footer/Footer.tsx
  src/components/mypage/ButtonGroup.tsx
  src/components/mypage/DeleteAccountModal.tsx
  src/components/mypage/UserInfo.tsx
  src/router.tsx
Labels: 📬 API, ⛰️ 윤정

#48 feat: 마이페이지 api 연동 및 코스 스크랩, 스크랩 취소 연동
  public/assets/stamp/bookhansan.svg
  public/assets/stamp/eungbongsan.svg
  public/assets/stamp/gwanaksan.svg
  public/assets/stamp/hallasan.svg
  public/assets/stamp/jooheulsan.svg
  public/assets/stamp/joowangsan.svg
  public/assets/stamp/manisan.svg
  public/assets/stamp/naejangsan.svg
  public/assets/stamp/naeyeonsan.svg
  public/assets/stamp/namsan.svg
  public/assets/stamp/palgongsan.svg
  public/assets/stamp/seolaksan.svg
  src/apis/course/CourseListApi.tsx
  src/apis/mypage/MypageApi.tsx
  src/components/common/filter/styled.ts
  src/components/common/item/CourseItem.tsx
  src/components/common/list/CourseList.styled.ts
  src/components/common/list/CourseList.tsx
  src/components/common/list/CrewList.styled.ts
  src/components/common/list/ReviewList.styled.ts
  src/components/common/list/ReviewList.tsx
  src/components/course/courseList/CourseListComp.tsx
  src/components/mypage/LikedList.tsx
  src/components/mypage/MyReviewList.tsx
  src/components/mypage/ScrapedList.tsx
  src/components/mypage/Stamp.tsx
  src/data/stamp.json
Labels: 📬 API, ⛰️ 윤정

#55 [Feat] 코스인포페이지 coursedata, sketchmap ➡️ json / coursereview ➡️ api 연동
  src/apis/course/courseInfo/CourseReviewApi.tsx
  src/components/common/card/styled.ts
  src/components/common/modal/styled.ts
  src/components/course/courseInfo/CourseData.tsx
  src/components/course/courseInfo/CourseReview.tsx
  src/components/course/courseInfo/SketchMap.tsx
  src/components/course/courseList/MountainReview.tsx
  src/data/course_ids.json
  src/hooks/useNaverMap.ts
  src/pages/course/CourseInfo.tsx
  src/types/mountainData.d.ts
  src/types/naverMap.d.ts
Labels: 📬 API, ⛰️ 동은
